version: '3.8'
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
      target: dist
    ports:
      - "5173:5173"
    env_file:
      - client/.env
    working_dir: /social_media/client
    command: ["npm", "run", "dev"]
    volumes:
      - ./client:/social_media/client

  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - server/.env
    working_dir: /social_media/server
    ports:
      - "3000:3000"
    command: ["node", "./src/index.js"]
    volumes:
      - ./server:/social_media/server 